apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "configserver.fullname" . }}
spec:
  replicas: {{ .Values.configserver.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "configserver.name" . }}
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ include "configserver.name" . }}
        release: {{ .Release.Name }}
    spec:
      containers:
        - name: {{ include "configserver.name" . }}
          image: "{{ .Values.configserver.image.repository }}:{{ .Values.configserver.image.tag }}"
          imagePullPolicy: {{ .Values.configserver.image.pullPolicy }}
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: "{{ .Values.configserver.env.SPRING_PROFILES_ACTIVE }}"
          ports:
            - containerPort: {{ .Values.configserver.service.port }}
          volumeMounts:
            - name: application-dev-yaml
              mountPath: /config/application-dev.yml
              subPath: application-dev.yml
            - name: application-yaml
              mountPath: /config/application.yml
              subPath: application.yml
      volumes:
        - name: application-dev-yaml
          configMap:
            name: application-dev-configmap
        - name: application-yaml
          configMap:
            name: application-configmap
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: application-dev-configmap
data:
  application-dev.yml: |
{{ .Files.Get .Values.configserver.configFiles.applicationDev | indent 4 }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: application-configmap
data:
  application.yml: |
{{ .Files.Get .Values.configserver.configFiles.applicationDefault | indent 4 }}